version: "3.7"
services:
  authdb:
    image: postgres:14.5
    container_name: practical-pg-auth
    restart: always
    environment:
      POSTGRES_USER: scalauser
      POSTGRES_PASSWORD: scalapass
      POSTGRES_DB: authdb
      PGDATA: /pgdata
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    networks:
      - wpnet
  eventstoredb:
    image: postgres:14.5
    container_name: practical-pg-eventstore
    restart: always
    environment:
      POSTGRES_USER: scalauser
      POSTGRES_PASSWORD: scalapass
      POSTGRES_DB: eventstoredb
      PGDATA: /pgdata
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "6432:5432"
    networks:
      - wpnet
  validationdb:
    image: postgres:14.5
    container_name: practical-pg-validation
    restart: always
    environment:
      POSTGRES_USER: scalauser
      POSTGRES_PASSWORD: scalapass
      POSTGRES_DB: validationdb
      PGDATA: /pgdata
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "7432:5432"
    networks:
      - wpnet
  graphdb:
    image: neo4j:4.4.12
    container_name: practical-neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/neostream
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - wpnet
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: practical-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wpnet
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: practical-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_ENABLE_AUTH: true
    networks:
      - wpnet
  kafka:
    image: bitnami/kafka:3.3
    container_name: practical-kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: practical-zookeeper:2181
    networks:
      - wpnet
networks:
  wpnet: {}
